version: "3.7"
services:
  starbound:
    image: jazy5552/starbound-server
    deploy:
      replicas: 1
      restart_policy:
        delay: 10m
        max_attempts: 10
    labels:
      starbound.destcription: "Peronal Starbound Server"
      starbound.name: "Starbound Server"
    networks:
      - starbound
    volumes:
      - "starbound-data:/steamcmd/"
    #ports:
      #- "21025:21025"

networks:
  starbound:
    external:
      name: "host"

volumes:
  starbound-data:

